controllers/ChatController.php
<?php

namespace app\controllers;

use app\behaviors\UpdateOnlineBehavior;
use app\helpers\AvatarResolver;
use app\models\ChatHistory;
use app\models\User;
use app\models\UserSearch;
use Yii;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\Response;

/**
 * Class ChatController
 * @package app\controllers
 */
class ChatController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            ['class' => UpdateOnlineBehavior::className()],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $chat_partners = $dataProvider->getModels();

        $this->layout = 'chat-layout';

        return $this->render('index', [
            'chat_partners' => $chat_partners,
        ]);
    }

    /**
     * Получает историю для отправителя сообщений
     * @param int $sender_id Отправитель сообщения
     * @return ChatHistory[]
     */
    public function actionHistory($sender_id)
    {
        header('Access-Control-Allow-Origin: *');
        Yii::$app->response->format = Response::FORMAT_JSON;
        $history = ChatHistory::find()->where(['sender_id' => $sender_id])->all();

        return $history;
    }

    public function actionSendMessage()
    {
        $request = Yii::$app->request;
        /** @var User $identity */
        $identity = Yii::$app->user->identity;
        $chat_partners = (new User)->getChatPartners();

        $model = new ChatHistory();
        $model->sender_id = $identity->id;

        if ($model->load($request->post()) && $model->save()) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'date' => Yii::$app->formatter->asTime($model->message_send_datetime),
                'text' => $model->text,
                'avatar' => $identity->avatar,
            ];
        }

        return $this->render('index', [
            'chat_partners' => $chat_partners,
        ]);
    }

    /**
     * @param int $id Идентификатор собеседника
     * @return string
     */
    public function actionGetMessages($id)
    {
        $history = (new ChatHistory)->getMessages($id);

        //Отмечаем как прочитнные

        /** @var ChatHistory $message */
        foreach ($history as $message) {
            if ($message->recipient_id == Yii::$app->user->identity->id){
                $message->read = 1;
                $message->save();
            }
        }


        return $this->renderAjax('messages', [
            'history' => $history,
        ]);
    }

    /**
     * Загрузка файлов в чат
     * @return array
     * @throws \yii\base\Exception
     */
    public function actionUploadFiles()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        /** @var User $identity */
        $identity = Yii::$app->user->identity;
        $request = Yii::$app->request;

        $recipient = $request->post('recipient');

        $chat_history = new ChatHistory();

        $uploaded_files = $chat_history->saveFiles($_FILES);


        //Добавляем ссылки на загруженные файлы в сообщение
        $file_icon = Html::img('/img/fi.png');
        foreach ($uploaded_files as $file_name => $file_path) {
            $chat_history->text .= Html::a($file_icon . '&nbsp;' . $file_name, $file_path, [
                    'data-pjax' => 0,
                    'target' => '_blank'
                ]) . '<br>';
        }

        $chat_history->sender_id = $identity->id;
        $chat_history->recipient_id = $recipient;

        if (!$chat_history->save()) {
            Yii::error($chat_history->errors, '_error');
            return ['success' => 0, 'data' => json_encode($chat_history->errors)];
        }

        return ['success' => 1];
    }

    /**
     * Получает и возвращает инфу о собеседнике в чате
     * @param $id
     * @return array
     */
    public function actionGetPartnerInfo($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $partner = User::findOne($id) ?? null;

        if (!$partner) {
            return ['success' => 0];
        }

        return [
            'success' => 1,
            'name' => $partner->name,
            'avatar' => AvatarResolver::getRealAvatarPath($partner->avatar),
            'work' => $partner->work_place,
        ];
    }

    /**
     * Запрос на поиск собеседников в окне чата
     * @return array|string
     */
    public function actionSearchPartners()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $search_text = Yii::$app->request->post('search_text');

        if (!$search_text) return ['success' => 0];

        $chat_partners = User::find()->andWhere(['LIKE', 'name', $search_text])->all();

        Yii::info('Найдено собеседников: ' . count($chat_partners), 'test');

       return $this->renderAjax('/chat/partner_list.php', [
           'chat_partners' => $chat_partners,
           'search_text' => $search_text
       ]);

    }
}

views/chat/index.php
<?php

use app\helpers\SmileHelper;
use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

$sender = Yii::$app->user->identity->id;
$base_url = Url::base(true);

\johnitvn\ajaxcrud\CrudAsset::register($this);
/**
 * @var $chat_partners User[]
 */

?>
<?php Pjax::begin(['id' => 'pjax-chat-container'], ['style' => 'width: 100%']) ?>

<div class="chat-header">
    <div class="chat-left-header">
        <div class="sidebar-header">
            <img src="/img/menu-logo.png" style="height: 25px; margin: 8px 8px;">
            <?= Html::a('Мир24', '#') ?>
            <?= Html::a('Skype', '#') ?>
            <?= Html::a('Дзен', '#') ?>
        </div>
    </div>
    <div class="chat-right-header">
        <div class="chat-right-header-center">
            <div class="partner-info">
                <div class="partner-avatar">
                    <?php echo Html::img('', ['id' => 'chat-head-partner-avatar']) ?>
                </div>
                <div class="partner-description">
                    <div class="partner-name">
                    </div>
                    <div class="partner-work">
                    </div>
                </div>
            </div>

            <div class="info-btn">
                <a href="#" id="profile-link">
                    <?= Html::img('/img/info.png'); ?>
                </a>
            </div>
        </div>

        <div class="profile-block">
            <?php if (Yii::$app->user->isGuest == false): ?>
                <!-- begin header navigation right -->
                <ul class="nav navbar-nav" style="
    height: 41px;">
                    <li class="dropdown navbar-user">
                        <a id="btn-dropdown_header" href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"
                           style="margin-top: -7px;">
                            <img src="/<?= Yii::$app->user->identity->getRealAvatarPath() ?>" data-role="avatar-view"
                                 alt="">
                            <?php
                            $login = Yii::$app->user->identity->login;

                            if (strlen($login) > 15) {
                                $login = iconv_substr($login, 0, 13, "UTF-8") . '...';
                            }
                            ?>
                            <span class="hidden-xs"><?= $login ?>
                                &nbsp;-&nbsp;$<?= Yii::$app->user->identity->balance_usd ?></span> <b class="caret"></b>
                        </a>
                        <div style="text-align: right;">
                            <ul class="dropdown-menu animated fadeInLeft">
                                <li> <?= Html::a('Счет', ['accruals/index']) ?> </li>
                                <li> <?= Html::a('Профиль', ['user/profile']) ?> </li>
                                <li> <?= Html::a('Выйти', ['/site/logout'], ['data-method' => 'post']) ?> </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            <?php endif; ?>
        </div>
    </div>
</div>

<div class="chat-main">
    <div class="chat-left">
        <?= $this->render('partner_list.php'); ?>
    </div>

    <div id="chat-center" class="chat-center">
        <?= $this->render('messages') ?>
    </div>

    <div class="chat-right" style="display: none">
        <?php $smiles = new SmileHelper(); ?>
        <?php foreach ($smiles->getSmiles() as $smile_text => $smile_img): ?>
            <div class="smile">
                <img src="<?= $smile_img ?>" alt="<?= str_replace('|', '', $smile_text) ?>">
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php Pjax::end() ?>


<?php

$url = 'https://miruwir.com:3000';
$userId = Yii::$app->user->identity->getId();

$script = <<<JS

var recipient = '';

var socket = io('{$url}?from=server&userId={$userId}');

getUrlVars();

socket.on('message', function(data){
    // var data = JSON.parse(data);
    // console.log(data);
    // alert(123);
    $.pjax.reload('#pjax-chat-list-container');
    updateListMessage();
});
 
$(document).keydown(function(e) {
    if(e.keyCode === 13) {
        e.preventDefault();
        if (e.target.id === 'chat-text'){
            sendMessage();
        } else if (e.target.name === 'search_recipient'){
            console.log('Ищем собеседников');
             var s_text = $('.search-recipient').val();
            $.post(
                '/chat/search-partners',
                {
                    'search_text': s_text
                },
                function(response) {
                    // $('.chat-left').detach();
                    $('.chat-left').html(response);
                    recipient = null;
                    updateListMessage();
                    changePartnerFromHead(0);
                }
            )
        }
        console.log(e.target.name);
    }
  });

$(document).on('click', '#chat-smile-btn', function(){
    var right_block = $('.chat-right');
    right_block.slideToggle(400);
    right_block.css('display', 'flex');
    changeLeftSize();
});

$(document).on('click', '.list-item', function(){
    $('.list-item').removeClass('active-partner');
    $(this).addClass('active-partner');
    recipient = $(this).attr('data-chat-id');
    console.log('selected: ' + recipient);
    updateListMessage();
    changePartnerFromHead(recipient);
    $(this).find($('.unread-msg')).hide();    
});

function updateListMessage(){
    $.get(
        '/chat/get-messages?id=' + recipient,
        function(response) {
            $('#chat-center').html(response);
             var scrollTop = $('.anchor').offset().top;
             $('#chat-center-messages').scrollTop(scrollTop);
             setTimeout(function() {
                $('#chat-text').focus();
            }, 500);
        }
    );
    return true;
}

function changePartnerFromHead(partner_id) {
    var name_block = $('.partner-name');
    var image_block = $('#chat-head-partner-avatar');
    var work_block = $('.partner-work');
    var profile_link = $('#profile-link');
    $.get(
        '/chat/get-partner-info',
        {
            id: partner_id
        },
        function(response) {
            // debugger;
            if (response['success'] === 1){
                image_block.attr('src', response['avatar']);
                name_block.html(response['name']);
                work_block.html(response['work']);
                profile_link.attr('href', '/user/view?id=' + partner_id)
            } else {    
                image_block.attr('src', '');
                name_block.html('');
                work_block.html('');
                profile_link.attr('href', '#')
            }
        }
    )
}

$(document).on('click', '#chat-send-btn', function(e) {
    e.preventDefault();
    sendMessage();

});

function sendMessage() {
    if (recipient === ''){
        alert('Не выбран получатель сообщения!');
        return false;
    }
    
    var text = $('#chat-text').html();
    
    if (text === ''){
        return false;
    }
    var sender = {$sender};

    $.post({
        url: 'https://miruwir.com:3000/message',
        data: { chatId: {$userId}, text: "test", receiverId: recipient },
        done: function(response){
            console.log(response, 'Response from socket server');
        },
    });

    $.post(
        '/chat/send-message',
        {
            'ChatHistory[sender_id]': sender,
            'ChatHistory[recipient_id]': recipient,
            'ChatHistory[text]': text
        },
        function(response) {
            console.log(response);
          $('#chat-text').val('');
          updateListMessage();
        }
    )
};

$(document).on('click', '.smile', function() {
    var text_input =  $('#chat-text');
    console.log('smile click');
    var img = $(this).find('img');
    console.log(img.attr('src'));
    console.log('Insert to ' + text_input.attr('id'));
    img.clone().appendTo('#' + text_input.attr('id'));
    
});

$(document).on('click', '#chat-upload-file-btn', function() {
    setTimeout(function(){
        $('#chat-btn-file').trigger('click');
    }, 500);
});


$(document).on('change', 'input[type=file]', function(){
    var files = this.files;
    console.log(files);
    if(typeof files === 'undefined') return;
    var data = new FormData();
    $.each(files, function(key, value) {
        data.append(key, value);
    });
    data.append('chat_file_upload', 1);
    data.append('recipient', recipient);
    
    $.ajax({
        url: '/chat/upload-files',
        type: 'POST',
        data: data,
        dataType: 'json',
        processData: false,
        contentType: false,
        success: function(response, status, jqXHR){
            if (typeof response.error === 'undefined'){
                updateListMessage();
            } else {
                console.log(status,jqXHR);
            }
            console.log(response);
        }
    })
});

function getUrlVars() {
    var vars = [], hash;
    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    
     setTimeout(function(){
        $("[data-chat-id='" + vars['user'] + "']").trigger('click');
    }, 500);
    return vars;
};

 $(document).on('resize', '.chat-left', function(){
    console.log('resized');
});
 
function changeLeftSize() {
    var target_with = $('.chat-left').width();
    $('.chat-left-header').css('width', target_with + 75);
}
JS;

$this->registerJs($script); ?>

views/chat/messages.php
<?php

/** @var $history \app\models\ChatHistory[] */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div id="chat-center-messages" class="chat-center-messages">
    <?php if (isset($history)): ?>
        <?php Yii::info($history, 'test'); ?>
        <?php /** @var \app\models\ChatHistory $message */
        foreach ($history as $message): ?>
            <?php if ($message->recipient_id == Yii::$app->user->identity->id): ?>
                <div class="chat-message chat-message-client">
                    <div class="message-image-wrapper">
                        <?php Yii::info('Avatar: ' . $message->sender->id, 'test') ?>
                        <img src="<?= $message->sender->avatar ?? 'https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg' ?>"
                             alt="">
                    </div>
                    <div class="message-wrapper">
                        <div class="message">
                            <p><?= $message->text; ?></p>
                            <span class="message-time"><?= $message->getFormattedDate(); ?></span>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <div class="chat-message chat-message-me">
                    <div class="message-image-wrapper">
                        <img src="<?= $message->sender->avatar ?? 'https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg' ?>"
                             alt="">
                    </div>
                    <div class="message-wrapper">
                        <div class="message">
                            <p><?= $message->text; ?></p>
                            <span class="message-time"><?= $message->getFormattedDate(); ?></span>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <p class="no-partner">Выберите собеседника</p>
    <?php endif; ?>
    <input type="file" id="chat-btn-file" multiple="multiple" accept=".txt,image/*" style="display: none">
    <div class="anchor"></div>
    <div class="chat-form">
        <?= Html::button('<i class="fa fa-plus-circle"></i>', [
            'id' => 'chat-upload-file-btn',
            'class' => 'chat-btn',
            'title' => 'Добавить',
        ]) ?>
        <?= Html::button('<i class="fa fa-smile-o"></i>', [
            'id' => 'chat-smile-btn',
            'class' => 'chat-btn',
            'title' => 'Смайлы',
        ]) ?>
        <?php $form = ActiveForm::begin(['id' => 'chat-form']) ?>
        <?php
        //        echo Html::input('text', 'chat_text', '', [
        //            'id' => 'chat-text',
        //            'autocomplete' => 'off',
        //            'placeholder' => 'Введите текст сообщения...'
        //        ])
        ?>
        <div id="chat-text" contenteditable="true"></div>
        <?= Html::button('<i class="fa fa-send"></i>', [
            'id' => 'chat-send-btn',
            'class' => 'chat-btn',
            'title' => 'Отправить',
        ]) ?>

        <?php ActiveForm::end() ?>
    </div>
</div>

views/chat/partner_list.php
<?php

use app\helpers\AvatarResolver;
use app\models\User;
use yii\helpers\Html;
use yii\widgets\Pjax;

/**@var $chat_partners User[] */
/** @var $search_text string */

if (!isset($chat_partners)) {
    $chat_partners = (new User)->getChatPartners();
}

if (!isset($search_text)) {
    $search_text = null;
}

usort($chat_partners, function($a, $b){
    // var_dump($a->id);
    // var_dump($a->getLastMessageChat($a->id));
    // exit;
    $aDate = strtotime($a->getLastMessageChat($a->id)['date']);
    $bDate = strtotime($b->getLastMessageChat($b->id)['date']);

    // $aUnread = $a->getUnreadMessagesCount();
    // $bUnread = $b->getUnreadMessagesCount();

    return $aDate < $bDate;
});

?>
<!--<div class="chat-left">-->
<div class="chat-search form-group">
    <?= Html::input('text', 'search_recipient', $search_text, [
        'class' => 'search-recipient',
        'placeholder' => 'Поиск...'
    ]) ?>
</div>
<?php Pjax::begin(['id' => 'pjax-chat-list-container']) ?>
<ul class="chat-list">
    <?php /** @var User $partner */
    foreach ($chat_partners as $partner): ?>
        <li class="list-item" data-chat-id="<?= $partner->id ?>">
            <a href="#">
                <div class="list-item-first">
                    <div class="<?= $partner->getStatus(); ?>"></div>
                    <img src="<?= AvatarResolver::getRealAvatarPath($partner->avatar, true) ?>"
                         alt="<?= $partner->name ?>">
                    <div class="list-item-first-info">
                        <h4 title=""><?= $partner->name ?></h4>
                        <p data-role="chat-last-message-text"><?= $partner->getLastMessage($partner->id)['message']; ?></p>
                    </div>
                </div>
                <div class="list-item-second">
                    <div class="time-last-msg"><?php
                        echo Yii::$app->formatter->asTime($partner->last_active_datetime);
                        // echo $partner->getLastMessageChat($partner->id)['date'];
                    ?></div>
                    <?php
                    $unread_count = $partner->getUnreadMessagesCount();
                    Yii::info('Собеседник: ' . $partner->name . '. Непрочитано: ' . $unread_count, 'test');
                    if ($unread_count): ?>
                        <div class="unread-msg"><?= $unread_count ?></div>
                    <?php endif; ?>
                </div>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
<?php Pjax::end() ?>
<!--</div>-->