controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\forms\ForgetPassword;
use app\models\forms\ResetPasswordForm;
use app\models\forms\SignupForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\forms\LoginForm;
use yii\helpers\Html;
use yii\helpers\VarDumper;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionTest()
    {
        $date = [
            [
                'value' => '1',
                'date' => '2020-03-16 13:44'
            ],
            [
                'value' => '2',
                'date' => '2020-03-16 13:16'
            ],
            [
                'value' => '2',
                'date' => '2020-03-16 13:55'
            ],
            [
                'value' => '3',
                'date' => '2020-03-16 13:33'
            ],
            [
                'value' => '4',
                'date' => '2020-03-16 13:22'
            ],
        ];

        usort($date, function($a, $b){
            $aDate = strtotime($a['date']);
            $bDate = strtotime($b['date']);

            return $aDate < $bDate;
        });

        VarDumper::dump($date, 10, true);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Для изменения пароля
     * @return array
     */
    public function actionResetPassword()
    {
        $request = Yii::$app->request;
        $user = Yii::$app->user->identity;
        $model = new ResetPasswordForm(['uid' => $user->id]);

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet) {
                return [
                    'title' => "Сменить пароль",
                    'content' => $this->renderAjax('reset-password-form', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-white pull-left btn-sm', 'data-dismiss' => "modal"]) .
                        Html::button('Изменить', ['class' => 'btn btn-primary btn-sm', 'type' => "submit"])

                ];
            } else if($model->load($request->post()) && $model->resetPassword()){
                Yii::$app->user->logout();
                return [
                    'title' => "Сменить пароль",
                    'content' => '<span class="text-success">Ваш пароль успешно изменен</span>',
                    'footer' => Html::button('Закрыть', ['class' => 'btn btn-white btn-sm', 'data-dismiss' => "modal"]),
                ];
            } else {
                return [
                    'title' => "Сменить пароль",
                    'content' => $this->renderAjax('reset-password-form', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-white pull-left btn-sm', 'data-dismiss' => "modal"]) .
                        Html::button('Изменить', ['class' => 'btn btn-primary btn-sm', 'type' => "submit"])

                ];
            }
        }
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = '@app/views/layouts/main-login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionForgetPassword()
    {
        $this->layout = '@app/views/layouts/main-login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new ForgetPassword();
        if ($model->load(Yii::$app->request->post()) && $model->sendNewPassword()) {
            Yii::$app->session->setFlash('success', 'На почту отправлен новый пароль');
            return $this->goBack();
        }
        return $this->render('forget-password', [
            'model' => $model,
        ]);
    }

    /**
     * Register action.
     *
     * @return string
     */
    public function actionRegister()
    {
        $this->layout = '@app/views/layouts/main-login.php';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }


        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Вы успешно зарегистрировались');
            (new LoginForm(['username' => $model->email, 'password' => $model->password]))->login();
            return $this->goHome();
        }
        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionApplications()
    {
        return $this->render('@app/views/_prototypes/applications');
    }

    public function actionAuto()
    {
        return $this->render('@app/views/_prototypes/auto');
    }

    public function actionAutoView()
    {
        return $this->render('@app/views/_prototypes/auto_view');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <!-- begin error -->
    <div class="error">
        <div class="error-code m-b-10"><?=$exception->statusCode?> <i class="fa fa-warning"></i></div>
        <div class="error-content">
            <div class="error-message"><?=$message?></div>
            <div class="error-desc m-b-20">
                Если это ошибка сервера. <br>
                Свяжитесь с тех поддержкой.
            </div>
            <div>
                <a href="/" class="btn btn-success">На главную</a>
            </div>
        </div>
    </div>
    <!-- end error -->

</div>

views/site/forget-password.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\forms\ForgetPassword */

$this->title = 'Востановить пароль';

$fieldOptions1 = [
    'inputTemplate' => "<div class='form__field'>{input}</div>"
];
?>

<div class="form-wrap">
    <div class="logo-wrap">
        <h1>ПО-БРАТСКИ</h1>
        <h2>МУЖСКАЯ ПАРИКМАХЕРСКАЯ</h2>
    </div>
    <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
    <?= $form
        ->field($model, 'email', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('email'), 'class' => 'form__input']) ?>
    <div class="login-buttons">
        <?= Html::submitButton('Отправить новый пароль', ['class' => 'btn-form primary small', 'name' => 'login-button']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Worker';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Авторизация';

$fieldOptions1 = [
    'inputTemplate' => "<div class='form__field'>{input}</div>"
];

$fieldOptions2 = [
    'inputTemplate' => "<div class='form__field'>{input}</div>"
];
?>



<div class="form-wrap">
    <div class="logo-wrap">
        <h1>ПО-БРАТСКИ</h1>
        <h2>МУЖСКАЯ ПАРИКМАХЕРСКАЯ</h2>
    </div>
    <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>
        <div class="form__wrap">
            <label class="form__label" for="#">Введите данные для авторизации </label>
            <?= $form
                ->field($model, 'username', $fieldOptions1)
                ->label(false)
                ->textInput(['value'=>'admin','placeholder' => $model->getAttributeLabel('email'), 'class' => 'form__input']) ?>

            <?= $form
                ->field($model, 'password', $fieldOptions2)
                ->label(false)
                ->passwordInput(['value'=>'admin','placeholder' => $model->getAttributeLabel('password'), 'class' => 'form__input']) ?>

            <div class="form__nav"><a class="form__link" href="<?= \yii\helpers\Url::toRoute(['site/forget-password']) ?>">Забыли пароль</a><a class="form__link" href="<?= \yii\helpers\Url::toRoute(['site/register']) ?>">Регистрация</a></div>
            <div class="form__footer">
                <?= Html::submitButton('Войти', ['class' => 'btn-form primary', 'name' => 'login-button']) ?>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Регистрация';

$fieldOptions1 = [
    'horizontalCssClasses' => [
        'error' => 'form__valid-text',
    ],
    'inputTemplate' => "<div class='form__field'>{input}</div>"
];

if(isset($_GET['ref_id'])){
    $refId = $_GET['ref_id'];
} else {
    $refId = null;
}


$model->ref_id = $refId;

?>

<style>
    label.control-label {
        color: #9e9e9e;
        font-weight: 400;
    }

    .field-signupform-work_status .form__field label{
        color: #9e9e9e;
    }
</style>

<div class="form-wrap">
    <div class="logo-wrap">
        <h1>ПО-БРАТСКИ</h1>
        <h2>МУЖСКАЯ ПАРИКМАХЕРСКАЯ</h2>
    </div>
    <label class="control-label" for="">Регистрация</label>
    <?php $form = ActiveForm::begin(['id' => 'register-form', 'enableClientValidation' => false], $options = ['class' => 'margin-bottom-0']); ?>
    <?= $form
        ->field($model, 'name', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('name'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'email', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('email'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'password', $fieldOptions1)
        ->label(false)
        ->passwordInput(['placeholder' => $model->getAttributeLabel('password'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'birth_date', $fieldOptions1)
        ->label()
        ->textInput(['type' => 'date', 'class' => 'form__input'],['placeholder' => $model->getAttributeLabel('birth_date')]) ?>
    <?= $form
        ->field($model, 'country', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('country'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'living_country', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('living_country'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'living_place', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('living_place'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'education', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('education'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'profession', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('profession'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'work_place', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('work_place'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'work_position', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('work_position'), 'class' => 'form__input']) ?>

    <?= $form
        ->field($model, 'work_status', $fieldOptions1)
        ->label($model->getAttributeLabel('work_status'))
        ->radioList(['да' => 'да',
            'нет' => 'нет',
            'возможно' => 'возможно',
        ],
            [
                'item' => function($index, $label, $name, $checked, $value) {

                    $return = '<label class="form__label form__label_radio" onclick="$(\'.form__label_radio_checked\').removeClass(\'form__label_radio_checked\'); $(this).addClass(\'form__label_radio_checked\')">';
                    $return .= '<input class="" type="radio" name="' . $name . '" value="' . $value . '" tabindex="'. $index .'">';
                    $return .= '<i></i>';
                    $return .= '<span>' . ucwords($label) . '</span>';
                    $return .= '</label>';

                    return $return;
                }
            ]
        ) ?>

    <?= $form
        ->field($model, 'phone', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('phone'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'interests', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('interests'), 'class' => 'form__input']) ?>
    <?= $form
        ->field($model, 'hobby', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('hobby'), 'class' => 'form__input']) ?>

    <?= $form
        ->field($model, 'ref_id', $fieldOptions1)
        ->label(false)
        ->textInput(['placeholder' => $model->getAttributeLabel('ref_id'), 'class' => 'form__input']) ?>

    <div class="form__footer">
        <?= Html::submitButton('Регистрация', ['class' => 'btn-form primary', 'name' => 'login-button']) ?>
    </div>

    <div class="login-buttons">
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/site/reset-password-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\forms\ResetPasswordForm */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'oldPassword') ?>
<?= $form->field($model, 'newPassword') ?>
<?= $form->field($model, 'repeatPassword') ?>

<?php if(!Yii::$app->request->isAjax): ?>
    <div class="form-group">
        <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>
    </div>
<?php endif; ?>

<?php ActiveForm::end(); ?>